version: "3"
services:
    codeign:
        build: .
        container_name: 'codeign'
        ports:
          - 80:80
        links:
          - codeign_mariadb
        volumes:
          - /Users/yajaru/Developing/www:/var/www/html
    codeign_mariadb:
        image: mariadb:10.5.8
        container_name: 'codeign_mariadb'
        ports:
          - 3306:3306
        volumes:
          - /Users/yajaru/Developing/dataBases/mysql:/var/lib/mysql
          - /Users/yajaru/Developing/dataBases/logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: codeigniter
          MYSQL_USER: codeign
          MYSQL_PASSWORD: rootcodeign
    codeign_myadmin:
        image: phpmyadmin/phpmyadmin:5.0.4
        container_name: 'codeign_phpmyadmin'
        links:
          - codeign_mariadb
        environment:
          PMA_HOST: codeign_mariadb
          PMA_PORT: 3306
        ports:
          - 8081:80
        volumes:
          - /Users/yajaru/Developing/sessions:/sessions

